services:
  mattermost: # запускается только для демо-режима
    image: mattermost/mattermost-preview:latest
    container_name: mattermost
    ports:
      - "8065:8065"
      - "8075:8075"
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS=matterpoll-bot
      - MM_CORSSETTINGS_ALLOWEDORIGINS=*
      - MM_CORSSETTINGS_ALLOWCREDENTIALS=true
    volumes:
      - ./mattermost/data:/var/lib/mattermost
      - ./mattermost/config:/mattermost/config
    networks:
      - my-network

  matterpoll-bot:
    build: .
    container_name: matterpoll-bot
    environment:
      MODE: "database" # по необходимости можно изменить на "memory"
      SERVER_URL: "http://mattermost:8065" # измените на свой домен при наличии
      BOT_SOCKET: ":4000"
      BOT_HOSTNAME: "matterpoll-bot" # если mattermost запускался не в демо-режима (не в составе Docker compose), то требуется изменить на действительный hostname бота
      DB_SOCKET: "tarantool:3301"
      TEAM_NAME: "your_team_name" # измените на свое имя команды
      BOT_TOKEN: "your_bot_token" # измените на свой токен
    ports:
      - "4000:4000"
    networks:
      - my-network
    depends_on:
      - tarantool
    tty: true

  tarantool:
    build: internal/storage/database/docker
    container_name: tarantool
    networks:
      - my-network
    tty: true

networks:
  my-network:
